### Get All Property
GET http://localhost:3000/property

### Get Property By Id
GET http://localhost:3000/property/2

### Create Property
POST http://localhost:3000/property
Accept: application/json
Content-Type: application/json

{
    "name": "Property 1",
    "description": "Property 1 description",
    "price": 1000,
    "address": "Property 1 address",
    "city": "Property 1 city",
    "state": "Property 1 state",
    "zip": "Property 1 zip",
    "bedrooms": 1,
    "bathrooms": 1,
    "square_feet": 1000,
    "lot_size": 1000,
    "garage": 1,
    "pool": true,
    "year_built": 2020,
    "property_type_id": 1
}

### Update Property
PUT http://localhost:3000/property/:id

### Delete Property
DELETE http://localhost:3000/property/:id

### Get All Property Type
GET http://localhost:3000/property-type

### Get Property Type By Id
GET http://localhost:3000/property-type/:id

### Create Property Type
POST http://localhost:3000/property-type

### Update Property Type
PUT http://localhost:3000/property-type/:id

### Delete Property Type
DELETE http://localhost:3000/property-type/:id