### Get All Property
GET http://localhost:3000/property

### Get Property By Id
GET http://localhost:3000/property/2?sort=true

### Create Property
POST http://localhost:3000/property
Accept: application/json
Content-Type: application/json

{
    "name": "Property 1",
    "description": "abc",
    "area": 100
}

### Update Property
PUT http://localhost:3000/property/1
Accept: application/json
Content-Type: application/json

{
    "name": "Property 1",
    "description": "11",
    "area": 100
}

### Delete Property
DELETE http://localhost:3000/property/:id

### Get All Property Type
GET http://localhost:3000/property-type

### Get Property Type By Id
GET http://localhost:3000/property-type/:id

### Create Property Type
POST http://localhost:3000/property-type

### Update Property Type
PUT http://localhost:3000/property-type/:id

### Delete Property Type
DELETE http://localhost:3000/property-type/:id